In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_rows', 10)
df = pd.read_csv("vacancies_balanced.csv",  sep=';')
df

,base_salary_max,base_salary_min,id_vacancy,region,requirements_qualifications,responsibilities,title
0,25100.0,25000.0,798406a2-abb4-11ea-94f4-bf2cfe8c828d,1600000000000,"Должен соблюдать нормы и правила, инструкции п...",1. Обеспечение безопасности судебной деятельно...,Администратор суда
1,21000.0,18000.0,08df1d56-e91b-11ea-a2f1-03fd6b4dc11f,1800000000000,"Муниципальный служащий, замещающий должность в...",Область профессиональной служебной деятельност...,ведущий специалист -эксперт отдела по развитию...
2,NaN,NaN,440c44e6-893b-11e7-88b9-037acc02728d,7500000000000,Высшее образование. Опыт работы на подземном р...,Должностные обязанности: | - Осуществлять руко...,Геолог на подземных горных работах
3,60000.0,60000.0,5a337c52-8e7a-11eb-9dd6-bf2cfe8c828d,300000000000,"Наличие опыта работы, ответственность дисципли...",Осуществляет организацию бухгалтерского учета ...,Заместитель главный бухгалтер
4,0.0,0.0,f968e6e6-899a-11e7-88b9-037acc02728d,3500000000000,"Необходимые умения| | Основные типы, конструкт...",Трудовые действия| | Ознакомление с конструкто...,Электросварщик ручной сварки
...,...,...,...,...,...,...,...
22975,NaN,15000.0,e04e1191-078c-11ea-b024-bf2cfe8c828d,6400000000000,NaN,NaN,Каменщик
22976,20735.0,NaN,941a3842-fe70-11ea-94f4-bf2cfe8c828d,6400000000000,NaN,NaN,Системный администратор
22977,NaN,15000.0,6952aea2-fa1e-11e9-b024-bf2cfe8c828d,6400000000000,NaN,NaN,Ведущий программист
22978,NaN,12200.0,65261a81-4da5-11ea-af61-bf2cfe8c828d,2000000000000,NaN,NaN,Программист
22979,NaN,25000.0,47e97ff2-cfc6-11e9-a3b9-bf2cfe8c828d,700000000000,NaN,NaN,Электрогазосварщик

In [5]:
df.base_salary_max.fillna("Unknown")

0        25100.0
1        21000.0
2        Unknown
3        60000.0
4            0.0
          ...
22975    Unknown
22976    20735.0
22977    Unknown
22978    Unknown
22979    Unknown
Name: base_salary_max, Length: 22980, dtype: object

In [18]:
df = df.dropna()

In [19]:
df.shape

(14534, 7)

In [42]:
df['requirements_qualifications'] = df['requirements_qualifications'].replace('нет', np.nan)

In [43]:
df = df.dropna()

In [44]:
df['requirements_qualifications'] = df['requirements_qualifications'].replace('не указано', np.nan)

In [45]:
df = df.dropna()

In [ ]:
df = df.drop([22887, 22885])

In [ ]:
df = df.drop('id_vacancy', axis=1)

In [47]:
df.tail()

,base_salary_max,base_salary_min,region,requirements_qualifications,responsibilities,title
22865,14000.0,14000.0,7400000000000,ОТВЕТСТВЕННОСТЬ,ДЕЛОПРОИЗВОДИТЕЛЬ,Делопроизводитель
22867,21000.0,20000.0,6600000000000,Опыт работы в 1С,Учет материалов,бухгалтер по материалам
22870,15163.0,15163.0,8900000000000,ответственность,ответственность,Делопроизводитель
22871,30000.0,30000.0,7400000000000,ОПЫТ ОТ 3 ЛЕТ,ВРАЧ-ЭНДОКРИНОЛОГ,Врач-эндокринолог
22883,50000.0,50000.0,7400000000000,ОТВЕТСТВЕННОСТЬ,КАРДИОЛОГ,Врач-кардиолог

In [58]:
summary_df = df.pivot_table(
    index='title', 
    values=['base_salary_min', 'base_salary_max'], 
    aggfunc='mean'
).reset_index()

# Считаем общее среднее по двум колонкам
summary_df['base_salary_avg'] = (summary_df['base_salary_min'] + summary_df['base_salary_max']) / 2
summary_df = summary_df[['title', 'base_salary_avg']]

In [59]:
summary_df.head()

                   title  base_salary_avg
0         1С-программист          30000.0
1  Android - разработчик          48000.0
2    Android разработчик          22500.0
3         BE Разработчик              0.0
4         DevOps инженер              0.0

In [60]:
df['base_salary_avg'].agg(['mean', 'median'])

mean      25258.266797
median    21500.000000
Name: base_salary_avg, dtype: float64

In [61]:
df.describe()

       base_salary_max  base_salary_min        region  base_salary_avg
count     14526.000000     14526.000000  1.452600e+04     14526.000000
mean      26546.310615     23970.222979  4.439632e+12     25258.266797
std       17589.941355     14210.734204  2.378082e+12     14935.427647
min           0.000000         0.000000  1.000000e+11         0.000000
25%       15000.000000     15000.000000  2.300000e+12     15000.000000
50%       22718.000000     20000.000000  4.700000e+12     21500.000000
75%       31000.000000     29906.000000  6.300000e+12     30000.000000
max      256830.000000    150000.000000  9.900000e+12    201795.000000